// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCsi3UCAPCybU97Go67oyFYde55dlI9Ik',
    appId: '1:174407953593:web:6f34fa34dcba79dcf2bf68',
    messagingSenderId: '174407953593',
    projectId: 'kafecraft-exam',
    authDomain: 'kafecraft-exam.firebaseapp.com',
    storageBucket: 'kafecraft-exam.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4CaN-JHgRQeR0vrbfCoYjAn4ze0q4tRU',
    appId: '1:174407953593:android:8481f91660b03bccf2bf68',
    messagingSenderId: '174407953593',
    projectId: 'kafecraft-exam',
    storageBucket: 'kafecraft-exam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD51G4Zqxw3wYNMSCSe6IHsfP_l8V1DpZE',
    appId: '1:174407953593:ios:9a058f45972cb641f2bf68',
    messagingSenderId: '174407953593',
    projectId: 'kafecraft-exam',
    storageBucket: 'kafecraft-exam.firebasestorage.app',
    iosBundleId: 'com.example.kafecraftExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD51G4Zqxw3wYNMSCSe6IHsfP_l8V1DpZE',
    appId: '1:174407953593:ios:9a058f45972cb641f2bf68',
    messagingSenderId: '174407953593',
    projectId: 'kafecraft-exam',
    storageBucket: 'kafecraft-exam.firebasestorage.app',
    iosBundleId: 'com.example.kafecraftExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCsi3UCAPCybU97Go67oyFYde55dlI9Ik',
    appId: '1:174407953593:web:2e0f7cbefc5c5beaf2bf68',
    messagingSenderId: '174407953593',
    projectId: 'kafecraft-exam',
    authDomain: 'kafecraft-exam.firebaseapp.com',
    storageBucket: 'kafecraft-exam.firebasestorage.app',
  );
}
